/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BipsRouteImport } from './routes/bips'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as SinaisRouteImport } from './routes/sinais'
import { Route as BancaRouteImport } from './routes/banca'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const BipsRoute = BipsRouteImport.update({ id: '/bips', path: '/bips', getParentRoute: () => rootRouteImport } as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({ id: '/configuracoes', path: '/configuracoes', getParentRoute: () => rootRouteImport } as any)
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport } as any)
const SimuladorRoute = SimuladorRouteImport.update({ id: '/simulador', path: '/simulador', getParentRoute: () => rootRouteImport } as any)
const SinaisRoute = SinaisRouteImport.update({ id: '/sinais', path: '/sinais', getParentRoute: () => rootRouteImport } as any)
const BancaRoute = BancaRouteImport.update({ id: '/banca', path: '/banca', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bips': typeof BipsRoute
  '/banca': typeof BancaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/simulador': typeof SimuladorRoute
  '/sinais': typeof SinaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bips': typeof BipsRoute
  '/banca': typeof BancaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/simulador': typeof SimuladorRoute
  '/sinais': typeof SinaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bips': typeof BipsRoute
  '/banca': typeof BancaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/simulador': typeof SimuladorRoute
  '/sinais': typeof SinaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bips' | '/banca' | '/configuracoes' | '/dashboard' | '/simulador' | '/sinais'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bips' | '/banca' | '/configuracoes' | '/dashboard' | '/simulador' | '/sinais'
  id: '__root__' | '/' | '/bips' | '/banca' | '/configuracoes' | '/dashboard' | '/simulador' | '/sinais'
  fileRoutesById: FileRoutesById
}
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/bips': { id: '/bips'; path: '/bips'; fullPath: '/bips'; preLoaderRoute: typeof BipsRouteImport; parentRoute: typeof rootRouteImport }
    '/banca': { id: '/banca'; path: '/banca'; fullPath: '/banca'; preLoaderRoute: typeof BancaRouteImport; parentRoute: typeof rootRouteImport }
    '/configuracoes': { id: '/configuracoes'; path: '/configuracoes'; fullPath: '/configuracoes'; preLoaderRoute: typeof ConfiguracoesRouteImport; parentRoute: typeof rootRouteImport }
    '/dashboard': { id: '/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof DashboardRouteImport; parentRoute: typeof rootRouteImport }
    '/simulador': { id: '/simulador'; path: '/simulador'; fullPath: '/simulador'; preLoaderRoute: typeof SimuladorRouteImport; parentRoute: typeof rootRouteImport }
    '/sinais': { id: '/sinais'; path: '/sinais'; fullPath: '/sinais'; preLoaderRoute: typeof SinaisRouteImport; parentRoute: typeof rootRouteImport }
  }
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BipsRoute: typeof BipsRoute
  BancaRoute: typeof BancaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  SimuladorRoute: typeof SimuladorRoute
  SinaisRoute: typeof SinaisRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  BipsRoute,
  BancaRoute,
  ConfiguracoesRoute,
  DashboardRoute,
  SimuladorRoute,
  SinaisRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
